# -*- coding: utf-8 -*-
"""CSC_404_Section3_0_InsertionSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cx3Lrn9hdbJ9uF-vnpp36TQADiZ-eJND
"""

print('Hello World!')

def insertion_sort(A):
  for i in range(1, len(A)):
    key = A[i]
    j = i - 1
    while j >= 0 and key < A[j]:
      A[j+1] = A[j]
      j -= 1
    A[j+1] = key
  return A

print('Jenny\'s List!')
L = [8,6,7,5,3,0,9]
print('Unsorted List:\t',L)
print('Sorted List:\t',insertion_sort(L))

import random

print('\nRandom List!')
L = [random.randint(0,100) for _ in range(100)]
print('Unsorted List:\t',L)
print('Sorted List:\t',insertion_sort(L))

