# -*- coding: utf-8 -*-
"""CSC_404_Section3_0_MergeSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mg5PhDhsxiijLDYuk6mwiW-BVu1LLsqf
"""

def merge(A,B):
  result = []
  i = j = 0

  # Compare various elements and merge them into a sorted list
  while i < len(A) and j < len(B):
    if A[i] < B[j]:
      result.append(A[i])
      i += 1
    else:
      result.append(B[j])
      j += 1

  # Add remaining elements
  result.extend(A[i:])
  result.extend(B[j:])

  return result

def merge_sort(L):
  n = len(L)
  if n <= 1:
    return L

  # Split the list into two halves and call merge_sort on the left and right portions
  mid = n//2
  left = merge_sort(L[:mid])
  right = merge_sort(L[mid:])
  return merge(left,right)

print('Jenny\'s List!')
L = [4,8,6,7,5,3,0,9]
print('Unsorted List:\t', L)
print('Sorted List:\t', merge_sort(L))

import random

print('\nRandom List!')
L = [random.randint(0,100) for _ in range(100)]
print('Unsorted List:\t', L)
print('Sorted List:\t', merge_sort(L))

